# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automation Test Execution 

on:
  push:
    branches: [ master ]

jobs:
  tests:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies    
      run: npm ci
    - name: Creating test suite  
      run: npm run create:suite SHEET=Regression --if-present
    - name: Test execution
      run: npm test
    - name: Generating execution report
      if: always()
      run: npx ts-node ./src/framework/reporter/HTMLReporter.ts  
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results
        
  generate_report:
    name: Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      id: download
      with:
        name: allure-results
        path: allure-results

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: ${{ github.run_number }}
        gh_pages: gh-pages
        allure_history: /allure-history

    - name: Deploy allure report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
